FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY dashboard-requirements.txt .

RUN pip install --no-cache-dir -r dashboard-requirements.txt

COPY dashboard ./dashboard
COPY models ./models
COPY data/processed ./data/processed
COPY data/zeek ./data/zeek

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
