import json
from pathlib import Path


# ============================================================
# PATHS
# ============================================================

INPUT_FILE = Path("data/zeek/zeek_features.json")
OUTPUT_FILE = Path("data/zeek/detections.json")


# ============================================================
# CONFIGURATION
# ============================================================

# Traffic thresholds
HIGH_PACKET_VOLUME = 1000
MEDIUM_PACKET_VOLUME = 500

HIGH_PACKET_RATE = 100
MEDIUM_PACKET_RATE = 50

HIGH_BYTES = 1_000_000
MEDIUM_BYTES = 500_000

HIGH_BYTES_PER_SECOND = 500_000
MEDIUM_BYTES_PER_SECOND = 250_000


# Sensitive service ports
SSH_PORT = 22
TELNET_PORT = 23
RDP_PORT = 3389

SENSITIVE_PORTS = {
    SSH_PORT,
    TELNET_PORT,
    RDP_PORT,
}


# ============================================================
# SAFE NUMBER CONVERSION
# ============================================================

def safe_float(value, default=0.0):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def safe_int(value, default=0):
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return default


# ============================================================
# THREAT CLASSIFICATION
# ============================================================

def classify_threat(indicators, destination_port, protocol):
    """
    Convert low-level detection indicators into
    a human-readable threat classification.

    The classification is based on the indicators
    already generated by the risk detection engine.
    """

    indicators = set(indicators or [])

    destination_port = safe_int(destination_port)

    protocol = str(
        protocol or "unknown"
    ).lower()

    # --------------------------------------------------------
    # Sensitive service anomalies
    # --------------------------------------------------------

    if "SSH_ANOMALY" in indicators:
        return "SSH Traffic Anomaly"

    if "TELNET_ANOMALY" in indicators:
        return "Telnet Traffic Anomaly"

    if "RDP_ANOMALY" in indicators:
        return "RDP Traffic Anomaly"

    # --------------------------------------------------------
    # TCP probing / scanning
    # --------------------------------------------------------

    if "TCP_PROBE_PATTERN" in indicators:
        return "Potential Port Scan"

    # --------------------------------------------------------
    # High traffic indicators
    # --------------------------------------------------------

    if "HIGH_PACKET_VOLUME" in indicators:
        return "High Packet Volume"

    if "HIGH_PACKET_RATE" in indicators:
        return "High Packet Rate"

    if "HIGH_TRAFFIC_VOLUME" in indicators:
        return "High Traffic Volume"

    if "HIGH_BANDWIDTH" in indicators:
        return "High Bandwidth Usage"

    # --------------------------------------------------------
    # Medium traffic indicators
    # --------------------------------------------------------

    if "MEDIUM_PACKET_VOLUME" in indicators:
        return "Elevated Packet Volume"

    if "MEDIUM_PACKET_RATE" in indicators:
        return "Elevated Packet Rate"

    if "MEDIUM_TRAFFIC_VOLUME" in indicators:
        return "Elevated Traffic Volume"

    if "MEDIUM_BANDWIDTH" in indicators:
        return "Elevated Bandwidth Usage"

    # --------------------------------------------------------
    # Connection anomalies
    # --------------------------------------------------------

    if "SUSPICIOUS_CONNECTION_STATE" in indicators:
        return "Suspicious Connection"

    # --------------------------------------------------------
    # Multiple indicators fallback
    # --------------------------------------------------------

    if "MULTIPLE_INDICATORS" in indicators:
        return "Multiple Suspicious Indicators"

    # --------------------------------------------------------
    # Generic suspicious traffic
    # --------------------------------------------------------

    if indicators:
        return "Suspicious Network Traffic"

    # --------------------------------------------------------
    # No indicators
    # --------------------------------------------------------

    return "Normal Traffic"


# ============================================================
# RISK DETECTION
# ============================================================

def calculate_risk(flow):

    score = 0

    reasons = []

    indicators = []

    # --------------------------------------------------------
    # Extract values
    # --------------------------------------------------------

    source_ip = flow.get(
        "source_ip",
        "unknown",
    )

    destination_ip = flow.get(
        "destination_ip",
        "unknown",
    )

    source_port = safe_int(
        flow.get("source_port")
    )

    destination_port = safe_int(
        flow.get("destination_port")
    )

    protocol = str(
        flow.get(
            "protocol",
            "unknown",
        )
    ).lower()

    total_packets = safe_float(
        flow.get("total_packets")
    )

    total_bytes = safe_float(
        flow.get("total_bytes")
    )

    total_packets_per_second = safe_float(
        flow.get("total_packets_per_second")
    )

    total_bytes_per_second = safe_float(
        flow.get("total_bytes_per_second")
    )

    conn_state = str(
        flow.get(
            "conn_state",
            "",
        )
    ).upper()

    history = str(
        flow.get(
            "history",
            "",
        )
    )

    # ========================================================
    # 1. PACKET VOLUME
    # ========================================================

    if total_packets >= HIGH_PACKET_VOLUME:

        score += 40

        reasons.append(
            "Very high packet volume"
        )

        indicators.append(
            "HIGH_PACKET_VOLUME"
        )

    elif total_packets >= MEDIUM_PACKET_VOLUME:

        score += 20

        reasons.append(
            "Elevated packet volume"
        )

        indicators.append(
            "MEDIUM_PACKET_VOLUME"
        )

    # ========================================================
    # 2. PACKET RATE
    # ========================================================

    if total_packets_per_second >= HIGH_PACKET_RATE:

        score += 30

        reasons.append(
            "High packet rate"
        )

        indicators.append(
            "HIGH_PACKET_RATE"
        )

    elif total_packets_per_second >= MEDIUM_PACKET_RATE:

        score += 15

        reasons.append(
            "Elevated packet rate"
        )

        indicators.append(
            "MEDIUM_PACKET_RATE"
        )

    # ========================================================
    # 3. TOTAL TRAFFIC VOLUME
    # ========================================================

    if total_bytes >= HIGH_BYTES:

        score += 20

        reasons.append(
            "High traffic volume"
        )

        indicators.append(
            "HIGH_TRAFFIC_VOLUME"
        )

    elif total_bytes >= MEDIUM_BYTES:

        score += 10

        reasons.append(
            "Elevated traffic volume"
        )

        indicators.append(
            "MEDIUM_TRAFFIC_VOLUME"
        )

    # ========================================================
    # 4. BANDWIDTH RATE
    # ========================================================

    if total_bytes_per_second >= HIGH_BYTES_PER_SECOND:

        score += 20

        reasons.append(
            "High bandwidth rate"
        )

        indicators.append(
            "HIGH_BANDWIDTH"
        )

    elif total_bytes_per_second >= MEDIUM_BYTES_PER_SECOND:

        score += 10

        reasons.append(
            "Elevated bandwidth rate"
        )

        indicators.append(
            "MEDIUM_BANDWIDTH"
        )

    # ========================================================
    # 5. SENSITIVE SERVICE PORT
    # ========================================================

    if destination_port in SENSITIVE_PORTS:

        if total_packets >= MEDIUM_PACKET_VOLUME:

            score += 25

            if destination_port == SSH_PORT:

                reasons.append(
                    "High traffic to SSH service port 22"
                )

                indicators.append(
                    "SSH_ANOMALY"
                )

            elif destination_port == TELNET_PORT:

                reasons.append(
                    "High traffic to Telnet service port 23"
                )

                indicators.append(
                    "TELNET_ANOMALY"
                )

            elif destination_port == RDP_PORT:

                reasons.append(
                    "High traffic to RDP service port 3389"
                )

                indicators.append(
                    "RDP_ANOMALY"
                )

    # ========================================================
    # 6. FAILED / UNUSUAL CONNECTION STATE
    # ========================================================

    suspicious_states = {
        "REJ",
        "RSTO",
        "RSTR",
        "RSTOS0",
        "S0",
    }

    if conn_state in suspicious_states:

        score += 10

        reasons.append(
            f"Suspicious connection state: {conn_state}"
        )

        indicators.append(
            "SUSPICIOUS_CONNECTION_STATE"
        )

    # ========================================================
    # 7. UNUSUAL TCP HISTORY
    # ========================================================

    if protocol == "tcp" and history:

        # A connection with SYN activity but no normal
        # completed handshake can indicate probing/scanning.
        if "S" in history and "A" not in history:

            score += 15

            reasons.append(
                "Incomplete TCP handshake pattern"
            )

            indicators.append(
                "TCP_PROBE_PATTERN"
            )

    # ========================================================
    # 8. MULTIPLE INDICATORS
    # ========================================================

    if len(indicators) >= 3:

        score += 10

        reasons.append(
            "Multiple suspicious traffic indicators detected"
        )

        indicators.append(
            "MULTIPLE_INDICATORS"
        )

    # ========================================================
    # CAP SCORE
    # ========================================================

    score = min(
        score,
        100,
    )

    # ========================================================
    # RISK LEVEL
    # ========================================================

    if score >= 60:

        risk_level = "HIGH"

    elif score >= 30:

        risk_level = "MEDIUM"

    else:

        risk_level = "LOW"

    # ========================================================
    # THREAT CLASSIFICATION
    # ========================================================

    threat_type = classify_threat(
        indicators,
        destination_port,
        protocol,
    )

    # ========================================================
    # RETURN
    # ========================================================

    return {
        "threat_type": threat_type,
        "risk_score": score,
        "risk_level": risk_level,
        "reasons": reasons,
        "indicators": indicators,
    }


# ============================================================
# MAIN
# ============================================================

def main():

    # --------------------------------------------------------
    # Check input
    # --------------------------------------------------------

    if not INPUT_FILE.exists():

        print(
            f"❌ Input file not found: {INPUT_FILE}"
        )

        return

    # --------------------------------------------------------
    # Load features
    # --------------------------------------------------------

    try:

        with open(
            INPUT_FILE,
            "r",
            encoding="utf-8",
        ) as file:

            flows = json.load(file)

    except json.JSONDecodeError as error:

        print(
            f"❌ Invalid JSON: {error}"
        )

        return

    except OSError as error:

        print(
            f"❌ Could not read input file: {error}"
        )

        return

    # --------------------------------------------------------
    # Validate list
    # --------------------------------------------------------

    if not isinstance(flows, list):

        print(
            "❌ Feature file must contain a JSON list."
        )

        return

    # --------------------------------------------------------
    # Analyze flows
    # --------------------------------------------------------

    detections = []

    for flow in flows:

        if not isinstance(flow, dict):

            print(
                "⚠️ Invalid flow detected. Skipping."
            )

            continue

        risk = calculate_risk(flow)

        detection = {
            "source_ip": flow.get(
                "source_ip"
            ),

            "destination_ip": flow.get(
                "destination_ip"
            ),

            "source_port": flow.get(
                "source_port"
            ),

            "destination_port": flow.get(
                "destination_port"
            ),

            "protocol": flow.get(
                "protocol"
            ),

            "threat_type": risk[
                "threat_type"
            ],

            "risk_score": risk[
                "risk_score"
            ],

            "risk_level": risk[
                "risk_level"
            ],

            "reasons": risk[
                "reasons"
            ],

            "indicators": risk[
                "indicators"
            ],
        }

        detections.append(
            detection
        )

    # --------------------------------------------------------
    # Save detections
    # --------------------------------------------------------

    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    try:

        with open(
            OUTPUT_FILE,
            "w",
            encoding="utf-8",
        ) as file:

            json.dump(
                detections,
                file,
                indent=2,
            )

    except OSError as error:

        print(
            f"❌ Could not save detections: {error}"
        )

        return

    # --------------------------------------------------------
    # Statistics
    # --------------------------------------------------------

    high = sum(
        1
        for item in detections
        if item["risk_level"] == "HIGH"
    )

    medium = sum(
        1
        for item in detections
        if item["risk_level"] == "MEDIUM"
    )

    low = sum(
        1
        for item in detections
        if item["risk_level"] == "LOW"
    )

    # Threat type statistics
    threat_counts = {}

    for item in detections:

        threat_type = item.get(
            "threat_type",
            "Unknown",
        )

        threat_counts[threat_type] = (
            threat_counts.get(
                threat_type,
                0,
            )
            + 1
        )

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    print(
        "\n🛡️ SentinelAI Zeek Detection Summary"
    )

    print(
        "------------------------------------"
    )

    print(
        f"Total flows: {len(detections)}"
    )

    print(
        f"HIGH: {high}"
    )

    print(
        f"MEDIUM: {medium}"
    )

    print(
        f"LOW: {low}"
    )

    print(
        "\nThreat Classification:"
    )

    print(
        "----------------------"
    )

    for threat_type, count in sorted(
        threat_counts.items()
    ):

        print(
            f"{threat_type}: {count}"
        )

    print(
        f"\nOutput: {OUTPUT_FILE.resolve()}"
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()